### ISSUE TITLE
Round-robin scheduler causes packet order scrambling on sender site

### ISSUE THREAD

**Issue by LeonardWalter** [telekom/mp-dccp#64] opened 2023-09-25 16:28 UTC
I added some debug statements to the output function on the sender site to find out why iperf would report out of order packets even when mpdccp reordering reported in-order transmission. 
[iperf_dbg.patch](https://github.com/telekom/mp-dccp/files/12718105/iperf_dbg.patch)

The debug messages show that packets are already scrambled on sender site.

![image](https://github.com/telekom/mp-dccp/assets/50204487/b9dec466-1ac2-47d5-aa3d-4e0ba4353cd9)
The debug messages dont work 100% of times but it is enough to make out that the iperf sequence numbers (orange) are not in order.

**Comment by NathalieRM** [comment] 2023-09-25 18:04
Hi @LeonardWalter 

something just came to my mind related o this issue, are you limiting the length of the Datagrams?, I ask because if the length is higher than the MTU -dccp header, the datagrams are segmented by iperf, and I don't know how the seq numbre inserted in the payload is handled in that case. If you are alerady limiting the lenght, could you please just share captures from the UDP and DCCP traffic?

Br, 

Nathalie

**Comment by LeonardWalter** [comment] 2023-09-25 18:13
I tried it with and without the -l parameter, the results were the same (iperf3 -c 10.0.42.1 -u -b 4M -t 1 -4 -l 1050)
dmesg | grep sending 

```
[ 1488.762647] sending 462 469 1126
[ 1488.762666] sending 464 470 1126
[ 1488.767439] sending 466 471 1138
[ 1488.777723] sending 467 472 1126
[ 1488.777803] sending 457 473 1126
[ 1488.777812] sending 459 474 1126
[ 1488.777830] sending 461 475 1126
[ 1488.777837] sending 463 476 1126
[ 1488.777842] sending 465 477 1126
[ 1488.785610] sending 468 478 1126
[ 1488.785625] sending 470 479 1126
[ 1488.785634] sending 472 480 1126
[ 1488.785642] sending 474 481 1126
[ 1488.789342] sending 476 482 1126
[ 1488.791041] sending 469 483 1126
[ 1488.791090] sending 471 484 1126
```
In the debug messages, the first value is the iperf seq number and the second one the mpdccp oall seq number. Last message is the dccp payload length

[iperf_scramble.zip](https://github.com/telekom/mp-dccp/files/12718258/iperf_scramble.zip)

**Comment by markusa** [comment] 2023-09-27 08:29
> something just came to my mind related o this issue, are you limiting the length of the Datagrams?, I ask because if the length is higher than the MTU -dccp header, the datagrams are segmented by iperf, and I don't know how the seq numbre inserted in the payload is handled in that case. If you are alerady limiting the lenght, could you please just share captures from the UDP and DCCP traffic?

Where is fragmentation really happen in this case? In iPerf or in IP Layer?

**Comment by NathalieRM** [comment] 2024-01-22 12:53
Hi @LeonardWalter , I have tested the PR #69 succesfully for the Round Robin scheduler. I attach here 2 screenshot from the UDP iperf sequence numbers, before and after applying the PR.

scrambled seq num before PR
![scrambled_seq_nu_before_PR](https://github.com/telekom/mp-dccp/assets/79710623/c1dfa089-c97b-42bf-aa0a-2413221929be)

In order seq num after PR
![Correct_seq_num_after_PR](https://github.com/telekom/mp-dccp/assets/79710623/ab363a22-17cc-4901-8637-287fe655fa62)

Just one additional question before closing the issue. I see you commented out the "dccp_ack_pending" condition from the Round-Robin, min SRTT and Redundant scheduler, but the condition is still there for the "default shceduler". Is there any specific reason for this? was the problem reproduced with the defautl scheduler?

**Comment by LeonardWalter** [comment] 2024-01-26 14:29
I checked this, and you are right. The default scheduler is currently not working as intended. Since dccp_ack_pending always returns true, packets are always sent to the first socket. 
Instead, if the socket is congested, data should be sent to other sockets.

I created a new PR that fixes this issue.

**Comment by LeonardWalter** [comment] 2024-01-26 14:36
I tested the PR by using iperf TCP over tunprox and with the update, I can see that traffic is also sent over my second link. With the old version, all traffic is sent over the first link, even when it is congested.

**Closed as completed** 2024-01-29 12:31 UTC
